openapi: 3.0.1
info:
  title: IP Echo
  version: 2.0.0
  description: A simple no-logs Vercel Edge function that returns the caller's IP address. You can read IP Echo's source code at [git.average.name](https://git.average.name/AverageHelper/ip-echo-vercel).
  license:
    name: GNU General Public License v3.0
    url: https://git.average.name/AverageHelper/ip-echo-vercel/src/branch/main/LICENSE
servers:
  - url: https://ipv4.average.name/api
paths:
  "/":
    get:
      tags:
        - echo
      summary: Get the caller's IP address
      operationId: ip
      security: [] # No security, public info
      responses:
        200:
          description: The caller's IP address is in the body.
          content:
            text/plain:
              schema:
                type: string
                example: 127.0.0.1
            application/json:
              schema:
                type: string
                example: "127.0.0.1"
        404:
          description: The caller's IP address could not be determined.
