# On PR to main, check that package.json and package-lock.json share the version, and that CHANGELOG.md is spec-compliant. Block otherwise.

when:
  - event: manual
  - event: pull_request
    branch: main

steps:
  check:
    name: Check Versions Match
    image: oven/bun:1.0.11
    commands:
      # For some reason, This script doesn't work in ts-node, but only in CI:
      - bun install
      - bun ./scripts/release.ts
